### ISSUE TITLE
is there a way to validate telegram channel id

### ISSUE THREAD

**Issue by ThinkDevStudios** [babenkoivan/telegram-notifications#3]
Hi! I integrated this package into my project to serve notifications to each of the managers registered on the system. Each manager can provide their own channel id. Everything works well but if the manager put in the wrong telegram channel id. The system will go into error. Is there a way to validate the provided channel id so that if it's not valid? The system does not have to try and send the notification. Hope you could help. Thank you!

**Comment by babenkoivan** [comment]
Hey, I think the easiest way is to try to send a test notification whenever you add a new chat id in the system:

```php
try {
   // try to notify the manager
} catch (Throwable $e) {
   // return an error if it occurs 
}
```
