### ISSUE TITLE
Laravel 8 install

### ISSUE THREAD

**Issue by mehrdad-parsa68** [babenkoivan/telegram-notifications#5]
Hi
I saw this exception during installing this package with the composer
  Problem 1
    - babenkoivan/telegram-notifications[v1.0.0, ..., v1.0.1] require guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires babenkoivan/telegram-notifications ^1.0 -> satisfiable by babenkoivan/telegram-notifications[v1.0.0, v1.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by babenkoivan** [comment]
Hi @mehrdad-parsa68, the package conflicts with the dependencies you use: it requires guzzle 6, but you already have guzzle 7. I plan to update the package: add PHP 8 support, and update the dependencies, but there is no estimation yet when it will be done.

**Comment by babenkoivan** [comment]
Hey @mehrdad-parsa68, PHP 8 support has been added in [v1.1.0](https://github.com/babenkoivan/telegram-notifications/releases/tag/v1.1.0). Please update the package version and feel free to reopen the issue if you stumble upon any problem related to the update.
